// 仅供本地测试：桩替换 obsidian 模块
export class App {}
export class TFile {}
export class TAbstractFile {}
export class Plugin {}
export class PluginSettingTab {}
export class Setting {}
export class Modal {}
export class Notice {}
export class TFolder {}
